package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Youtube search test")
    void generatedTest() {
        step("open https://www.youtube.com/", () -> {
            // todo
        });

        step("click on search line and paste \"selenide\"", () -> {
            // todo
        });

        step("click on enter or button search", () -> {
            // todo
        });

        step("сheck what's in the address bar link (\"https://www.youtube.com/results?search_query=selenide\")", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.youtube.com/'", () ->
            open("https://www.youtube.com/"));

        step("Page title should have text 'Bevor Sie zu YouTube weitergehen'", () -> {
            String expectedTitle = "Bevor Sie zu YouTube weitergehen";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.youtube.com/'", () ->
            open("https://www.youtube.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}